spring.application.name=Gestion de Empleados

# Puerto del servidor
server.port=8080

# --- CONFIGURACIÓN DE BASE DE DATOS H2 (Modo Archivo / Persistente) ---
# Esto crea una carpeta llamada "data" en el proyecto con el archivo de la BD
spring.datasource.url=jdbc:h2:file:./data/empleados_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin1234

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
# Crea o actualiza las tablas de la base de datos automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- CONSOLA WEB DE H2 ---
# Para que el profesor pueda entrar a http://localhost:8080/h2-console y ver los datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Para que Spring Security no bloquee la consola de H2
spring.h2.console.settings.web-allow-others=true